"""add image_url to Post

Revision ID: 53c9b02b9a0d
Revises: a1a67d405755
Create Date: 2025-04-30 15:45:32.800539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53c9b02b9a0d'
down_revision = 'a1a67d405755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('category', sa.Enum('Climate Change', 'Conservation', 'Sustainability', 'Renewable Energy', 'Wildlife', 'Pollution', name='category'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
